### ISSUE TITLE
Shrink dependencies including boost

### ISSUE THREAD

**Issue by nlpguyz** [nlpguyz/hackerskeyboard#21]
Current total size is 1.8G, which is too big.

**Comment by sherylynn** [comment]
![qq 20180228101639](https://user-images.githubusercontent.com/1698595/36766378-95e87a18-1c70-11e8-937f-5408a7fe55b4.png)
最后有这么大，另外第一次构建时候会占用android studio 大量虚拟机内存（studio64.option需要调大内存大小）不然会卡在build symbol这一步

**Comment by nlpguyz** [comment]
Problem is solved
