### ISSUE TITLE
在虚拟机(android x86)中,中文输入法键入字符不被输入法获取

### ISSUE THREAD

**Issue by sherylynn** [nlpguyz/hackerskeyboard#22]
使用最新版本，自己编译apk安装
在虚拟机(android x86)中,中文输入法键入字符不被输入法获取，字符直接自动上屏幕
怀疑是虚拟机默认连接了物理键盘，而物理键盘的键入没有转化成中文字词，直接出英文字母

不过如果按触摸一样单击hackerskeyboard上键盘字母按钮，是可以出字的

下一步尝试实体机androidx86链接物理键盘时使用hackerskeyboard时候能否出字（估计表现会一致）

**Comment by nlpguyz** [comment]
中文模式应把实体键盘视为软键盘处理。需要修改LatinIME.java相关代码，调用数isCJK()检测当前输入法语言。

**Comment by nlpguyz** [comment]
外接鍵盤打字的問題已經解決了。如何上屏需要研究一下再決定。
