### ISSUE TITLE
希望收录98五笔方案

### ISSUE THREAD

**Issue by omgredfog** [nlpguyz/hackerskeyboard#64]
码表取自98五笔资源库，98方案已无版权与专利约束：

[98五笔方案](https://github.com/omgredfog/98wubi-tables)

**Comment by nlpguyz** [comment]
据报无法部署，待调试

**Comment by omgredfog** [comment]
> 据报无法部署，待调试

我查了一下文件，原来是「dependencies」里引入了不相关的文件，原因是我发的配置文件有问题，已经将这个不合法的引用删掉了，现在已经可以正常部署了。

**Comment by nlpguyz** [comment]
https://github.com/nlpguyz/hackerskeyboard/commit/fcfdd727a114f65db427244d1a81372fa1a0d41e
